set-window-option -g mode-keys vi # use vi keys in tmux
set -sg escape-time 0

bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h resize-pane -L 2
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-l resize-pane -R 2

# Screen option
# set -g default-terminal "screen-256color"

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Border colours
set -g pane-border-style fg=colour57
set -g pane-active-border-style "bg=colour255 fg=colour57"
# set-option -g mouse on

bind F source-file ~/.tmux.macro.4pane.conf \; display-message "Applied 4-pane macro"
bind E source-file ~/.tmux.macro.8pane.conf \; display-message "Applied 8-pane macro"
